Add API version to API endpoints
OpenBrickProtocolFoundation/lobby pull request #4
Opened 2024-02-12 23:41 UTC by Totto16

- fix `requirements.txt`, since `jwt` and sub-dependencies were missing

Suggestion for the API:
Since this API isn't stable yet, I suggest adding a version endpoint, so that clients, that implement communication with this API can refer to that.

We can go against SemVer and say, that every change to the version below "1.0.0" is a potential breaking change and then bump the version to "1.0.0" after the API is stable and then follow SemVer guidelines for stability.

This helps clients massively, if they have the ability to connect to different Servers, so that they can determine which api version the server has and if the client supports the server.

I implemented that, by adding a `/version` endpoint, that returns the version, which is set to "0.1.0" atm.

2024-02-12 23:43 UTC, Totto16 commented
Ci fail is not the fault of this PR, it didn't work before either

2024-02-13 17:55 UTC, mgerhold requested changes
You're totally right when you say that we need some concept of a "version". But I think it's to early in the development process as of yet. I assume that a lot is going to change and already starting to version it would only increase the amount of work needed to maintain the project. So let's postpone this to a later point in time.
I'd like to merge your changes regarding `requirements.txt`, though.

2024-02-13 17:55 UTC, mgerhold commented on lobby/main.py
>  app = Flask(__name__)
```suggestion

app = Flask(__name__)
```

2024-02-13 17:55 UTC, mgerhold commented on lobby/main.py
> +
```suggestion
```

2024-02-13 17:59 UTC, Totto16 commented
> You're totally right when you say that we need some concept of a "version". But I think it's to early in the development process as of yet. I assume that a lot is going to change and already starting to version it would only increase the amount of work needed to maintain the project. So let's postpone this to a later point in time. I'd like to merge your changes regarding `requirements.txt`, though.

Seems goof to me, but instead of adding the version and removing it again by commits, I just remove the commit adding it

2024-02-13 18:51 UTC, mgerhold approved these changes

2024-02-13 18:52 UTC, merged